Repository woowacourse-teams/2021-drop-the-code, pull requests merged in 2021-07, with the labels that each got.

#3 프론트엔드 개발환경을 설정한다.
  frontend/.browserslistrc
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.common.ts
  frontend/webpack.dev.ts
  frontend/webpack.prod.ts
Labels: FE, chore

#15 버튼 컴포넌트 구현 및 테마 설정
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/index.tsx
  frontend/src/types/styled.d.ts
  frontend/src/utils/constants/color.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, chore, feature

#17 헤더, 플렉스 박스 컴포넌트 구현
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/shared/Flexbox/Flexbox.tsx
  frontend/src/utils/constants/size.ts
Labels: FE, chore, feature

#20 토글 버튼 추가
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/types/styled.d.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, feature

#21 셀렉트 컴포넌트 구현
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Select/Select.stories.tsx
  frontend/src/components/shared/Select/Select.tsx
Labels: FE, feature

#22 플로팅 메뉴 버튼 컴포넌트 구현 및 스토리 작성
  frontend/package.json
  frontend/src/components/FloatingMenuButton/FloatingMenuButton.stories.tsx
  frontend/src/components/FloatingMenuButton/FloatingMenuButton.tsx
  frontend/src/utils/constants/size.ts
Labels: FE, feature

#25 인풋 컴포넌트 구현 및 스토리 작성
  frontend/src/components/shared/Input/Input.stories.tsx
  frontend/src/components/shared/Input/Input.tsx
Labels: FE, feature

#26 텍스트에리어 컴포넌트 구현 및 스토리 작성
  frontend/src/components/shared/Textarea/Textarea.stories.tsx
  frontend/src/components/shared/Textarea/Textarea.tsx
Labels: FE, feature

#31 프로젝트 환경 설정, 도메인 설계, API 문서 자동화
  backend/.gitignore
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/DropTheCodeApplication.java
  backend/src/main/java/com/wootech/dropthecode/config/JpaConfig.java
  backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/domain/BaseEntity.java
  backend/src/main/java/com/wootech/dropthecode/domain/Language.java
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/Progress.java
  backend/src/main/java/com/wootech/dropthecode/domain/Review.java
  backend/src/main/java/com/wootech/dropthecode/domain/Role.java
  backend/src/main/java/com/wootech/dropthecode/domain/Skill.java
  backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/LanguageSkill.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/TeacherLanguage.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/TeacherSkill.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/ReviewCreateRequest.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/TeacherRegistrationRequest.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ProfileResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ReviewResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ReviewsResponse.java
  backend/src/main/java/com/wootech/dropthecode/exception/ErrorResponse.java
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application-test.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/static/cookie-header.adoc
  backend/src/main/resources/static/docs/asciidoc/api.html
  backend/src/test/java/com/wootech/dropthecode/DropTheCodeApplicationTests.java
  backend/src/test/java/com/wootech/dropthecode/controller/AutoMemberControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestDocsMockMvcUtils.java
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
Labels: BE, feature

#32 아바타 컴포넌트 구현
  frontend/src/components/shared/Avatar/Avatar.stories.tsx
  frontend/src/components/shared/Avatar/Avatar.tsx
Labels: FE, feature

#34 파비콘 및 로고 추가
  frontend/babel.config.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/assets/logo.svg
  frontend/webpack.common.ts
Labels: FE, chore, feature

#35 네비게이션 및 Route 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/logo.svg
  frontend/src/components/AuthRoute/PrivateRoute.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Navigation/Navigation.stories.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/index.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/ReviewHistory/ReviewHistory.tsx
  frontend/src/pages/ReviewRequest/ReviewRequest.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/types/assets.d.ts
  frontend/src/types/route.d.ts
  frontend/src/types/styled.d.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/theme.ts
  frontend/webpack.common.ts
Labels: FE, feature

#36 리뷰어 카드 컴포넌트를 구현한다.
  frontend/.storybook/preview.js
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Navigation/Navigation.stories.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/Reviewer/ReviewerCard.stories.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/components/shared/Avatar/Avatar.tsx
  frontend/src/components/shared/Chip/Chip.stories.tsx
  frontend/src/components/shared/Chip/Chip.tsx
Labels: FE, feature

#33 테스트 프로파일 설정
  backend/build.gradle
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/Role.java
  backend/src/main/java/com/wootech/dropthecode/dto/TechSpec.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/TeacherRegistrationRequest.java
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/main/resources/static/cookie-header.adoc
  backend/src/main/resources/static/docs/api.html
  backend/src/main/resources/static/docs/asciidoc/api.html
  backend/src/test/java/com/wootech/dropthecode/DropTheCodeApplicationTests.java
  backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestDocsMockMvcUtils.java
  backend/src/test/resources/org/springframework/restdocs/templates/asciidoctor/auto-method-path.snippet
Labels: BE, feature

#38 메인페이지 조회 기능 구현 및 mock data 적용
  frontend/src/App.tsx
  frontend/src/__mock__/filter.ts
  frontend/src/__mock__/reviewers.ts
  frontend/src/assets/logo.svg
  frontend/src/components/FloatingMenuButton/FloatingMenuButton.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/Flexbox/Flexbox.tsx
  frontend/src/pages/Main/Main.stories.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/types/reviewer.d.ts
  frontend/src/types/styled.d.ts
  frontend/src/utils/constants/color.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, feature

#46 폰트를 IBMPlexSansKR-Regular으로 변경
  frontend/public/index.html
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/shared/Chip/Chip.tsx
Labels: FE, refactor

#47 CareerPicker 컴포넌트 구현
  frontend/src/components/CareerPicker/CareerPicker.stories.tsx
  frontend/src/components/CareerPicker/CareerPicker.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.stories.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/pages/Main/Main.tsx
Labels: FE, feature

#53 텍스트박스 컴포넌트 구현 및 스토리 작성
  frontend/src/components/shared/TextBox/TextBox.stories.tsx
  frontend/src/components/shared/TextBox/TextBox.tsx
Labels: FE, feature

#51 Github OAuth 관련 컴포넌트 구현
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/lg-white-github-logo.png
  frontend/src/assets/sm-black-github-logo.png
  frontend/src/components/CareerPicker/CareerPicker.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/ModalProvider/Modal.stories.tsx
  frontend/src/components/ModalProvider/Modal.tsx
  frontend/src/components/ModalProvider/ModalPortal.tsx
  frontend/src/components/ModalProvider/ModalProvider.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/OAuth/GithubOAuth.stories.tsx
  frontend/src/components/OAuth/GithubOAuth.tsx
  frontend/src/components/OAuth/OAuthReceiver.tsx
  frontend/src/components/Reviewer/ReviewerCard.stories.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/components/shared/Avatar/Avatar.tsx
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/Chip/Chip.stories.tsx
  frontend/src/components/shared/Chip/Chip.tsx
  frontend/src/hooks/useModalContext.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/types/assets.d.ts
  frontend/src/types/route.d.ts
  frontend/src/types/styled.d.ts
  frontend/src/types/styled/common.d.ts
  frontend/src/types/styled/components.d.ts
  frontend/src/types/styled/index.d.ts
  frontend/src/utils/constants/color.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/theme.ts
  frontend/webpack.common.ts
  frontend/webpack.dev.ts
  frontend/webpack.prod.ts
Labels: FE, discussion, feature, refactor

#54 refresh plugin 추가
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.ts
  frontend/webpack.dev.ts
Labels: FE, chore

#55 선생님 목록 조회 기능 구현
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/config/CodeReviewConfig.java
  backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java
  backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java
  backend/src/main/java/com/wootech/dropthecode/domain/BaseEntity.java
  backend/src/main/java/com/wootech/dropthecode/domain/Language.java
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/Review.java
  backend/src/main/java/com/wootech/dropthecode/domain/Skill.java
  backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/LanguageSkill.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/TeacherLanguage.java
  backend/src/main/java/com/wootech/dropthecode/domain/bridge/TeacherSkill.java
  backend/src/main/java/com/wootech/dropthecode/dto/TechSpec.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/TeacherFilterRequest.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/LanguageResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/MemberResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ProfileResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/SkillResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherPaginationResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TechSpecResponse.java
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/wootech/dropthecode/repository/MemberRepository.java
  backend/src/main/java/com/wootech/dropthecode/repository/SkillRepository.java
  backend/src/main/java/com/wootech/dropthecode/repository/TeacherProfileRepository.java
  backend/src/main/java/com/wootech/dropthecode/service/TeacherService.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application-oauth.properties
  backend/src/main/resources/application-test.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/static/docs/api.html
  backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestDocsMockMvcUtils.java
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
Labels: BE

#61 메인페이지 리팩토링 및 더 보기 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/__mock__/filter.ts
  frontend/src/__mock__/reviewers.ts
  frontend/src/apis/apiClient.ts
  frontend/src/apis/reviewer.ts
  frontend/src/components/OAuth/GithubOAuth.tsx
  frontend/src/components/OAuth/OAuthReceiver.tsx
  frontend/src/components/Reviewer/ReviewerCard.stories.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/hooks/useLanguageList.ts
  frontend/src/hooks/useReviewerList.ts
  frontend/src/hooks/useReviewerListOptions.ts
  frontend/src/pages/Main/LanguageList.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/ReviewerList.tsx
  frontend/src/types/reviewer.d.ts
  frontend/src/types/styled/components.d.ts
  frontend/src/utils/constants/theme.ts
  frontend/src/utils/formatter.ts
  frontend/webpack.common.ts
  frontend/webpack.dev.ts
  frontend/webpack.prod.ts
Labels: FE, discussion, feature, refactor

#63 메인 페이지 UI 수정
  frontend/src/App.tsx
  frontend/src/assets/logo.svg
  frontend/src/components/CareerPicker/CareerPicker.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/Chip/Chip.tsx
  frontend/src/hooks/useReviewerList.ts
  frontend/src/hooks/useReviewerListOptions.ts
  frontend/src/pages/Main/LanguageList.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/ReviewerList.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
  frontend/src/types/reviewer.d.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, refactor

#94 스토리북 환경에서 react-refresh 플러그인 관련 설정 추가
  frontend/.storybook/main.js
Labels: FE, fix

#93 사용하지 않는 코드 삭제 및 코드 순서 변경
  frontend/src/hooks/useLanguageList.ts
  frontend/src/pages/Main/LanguageList.tsx
Labels: FE, refactor

#97 JWT 토큰 검증 인터셉터 추가 & 테스트
  backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java
  backend/src/main/java/com/wootech/dropthecode/config/auth/AuthenticationInterceptor.java
  backend/src/main/java/com/wootech/dropthecode/config/auth/GetAuthenticationInterceptor.java
  backend/src/main/java/com/wootech/dropthecode/config/auth/service/AuthService.java
  backend/src/main/java/com/wootech/dropthecode/config/auth/util/AuthorizationExtractor.java
  backend/src/main/java/com/wootech/dropthecode/config/auth/util/JwtTokenProvider.java
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/exception/AuthorizationException.java
  backend/src/main/java/com/wootech/dropthecode/exception/DropTheCodeException.java
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/wootech/dropthecode/config/auth/AuthenticationInterceptorTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java
Labels: BE, feature

#113 리뷰어 등록 페이지 UI 및 기능 구현
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/src/App.tsx
  frontend/src/apis/reviewer.ts
  frontend/src/assets/close.svg
  frontend/src/components/Auth/AuthRoute/AuthRoute.tsx
  frontend/src/components/FormProvider/FormProvider.tsx
  frontend/src/components/FormProvider/InputField.tsx
  frontend/src/components/FormProvider/TextareaField.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/shared/Avatar/Avatar.stories.tsx
  frontend/src/components/shared/Input/Input.stories.tsx
  frontend/src/components/shared/Input/Input.tsx
  frontend/src/components/shared/TextBox/TextBox.tsx
  frontend/src/components/shared/Textarea/Textarea.stories.tsx
  frontend/src/components/shared/Textarea/Textarea.tsx
  frontend/src/hooks/useFormContext.ts
  frontend/src/pages/Main/Main.stories.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.stories.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/pages/ReviewerRegister/SpecPicker.tsx
  frontend/src/types/reviewer.d.ts
  frontend/src/utils/constants/message.ts
  frontend/src/utils/constants/path.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/standard.ts
  frontend/src/utils/validators/reviewerRegisterForm.ts
Labels: FE, feature, fix

#118 chore: 커밋 전 husky, lint-staged 코드를 수정하는 깃훅 설정
  .husky/pre-commit
  frontend/.lintstagedrc.json
  frontend/package-lock.json
  frontend/package.json
Labels: FE, chore

#124 리뷰 요청 모달 UI 및 기능 구현 및 스토리 작성
  frontend/.storybook/preview.js
  frontend/src/apis/review.ts
  frontend/src/components/Auth/OAuth/GithubOAuth.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/ModalProvider/Modal.tsx
  frontend/src/hooks/useLanguageList.ts
  frontend/src/hooks/useReviewerList.ts
  frontend/src/index.tsx
  frontend/src/pages/Main/LanguageList/LanguageList.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/ReviewerList/ReviewerList.tsx
  frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx
  frontend/src/pages/ReviewRequest/ReviewRequest.tsx
  frontend/src/pages/ReviewerDetail/ReviewRequest.stories.tsx
  frontend/src/pages/ReviewerDetail/ReviewRequest/ReviewRequest.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/types/review.ts
  frontend/src/utils/constants/message.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/constants/standard.ts
  frontend/src/utils/validators/reviewRequestValidators.ts
  frontend/src/utils/validators/reviewerRegisterValidators.ts
Labels: FE, feature

#127 access token 갱신 & 로그아웃 & 로그인, members/me 응답에 id 추가
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java
  backend/src/main/java/com/wootech/dropthecode/controller/AuthController.java
  backend/src/main/java/com/wootech/dropthecode/controller/OauthController.java
  backend/src/main/java/com/wootech/dropthecode/controller/auth/util/JwtTokenProvider.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/RefreshTokenRequest.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/AccessTokenResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/LoginResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/MemberResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/OauthTokenResponse.java
  backend/src/main/java/com/wootech/dropthecode/service/AuthService.java
  backend/src/main/java/com/wootech/dropthecode/service/OauthService.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application-test.properties
  backend/src/test/java/com/wootech/dropthecode/config/auth/controller/OauthControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/config/auth/service/AuthServiceTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/AuthControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/util/RestDocsMockMvcUtils.java
  backend/src/test/java/com/wootech/dropthecode/service/AuthServiceTest.java
  backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
Labels: BE, feature, refactor

#125 헤더의 z-index 제거 및 테마로 z-index 관리
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/shared/Navigation/Navigation.tsx
  frontend/src/types/styled/common.d.ts
  frontend/src/utils/constants/size.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, fix

#134 히스토리 페이지 UI , 스토리, 기능 구현
  frontend/src/apis/review.ts
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/Review/ReviewCard.stories.tsx
  frontend/src/components/Review/ReviewCard.tsx
  frontend/src/components/Reviewer/ReviewerCard.tsx
  frontend/src/pages/History/History.stories.tsx
  frontend/src/pages/History/History.tsx
  frontend/src/pages/History/ReviewList/ReviewList.tsx
  frontend/src/pages/ReviewDetail/ReviewDetail.tsx
  frontend/src/pages/ReviewHistory/ReviewHistory.tsx
  frontend/src/types/review.d.ts
  frontend/src/types/review.ts
  frontend/src/utils/constants/path.ts
  frontend/src/utils/constants/route.ts
  frontend/src/utils/formatter.ts
Labels: FE, feature

#137 리뷰어 상세 페이지 UI, 기능, 스토리 구현
  frontend/src/__mock__/reviewers.ts
  frontend/src/apis/reviewer.ts
  frontend/src/assets/sm-white-github-logo.png
  frontend/src/components/LanguageList/LanguageList.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.stories.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/Reviewer/ReviewerCard/ReviewerCard.stories.tsx
  frontend/src/components/Reviewer/ReviewerCard/ReviewerCard.tsx
  frontend/src/components/Reviewer/ReviewerContentBox/ReviewerContentBox.stories.tsx
  frontend/src/components/Reviewer/ReviewerContentBox/ReviewerContentBox.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.stories.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/components/Reviewer/ReviewerList/ReviewerList.tsx
  frontend/src/hooks/useLanguageList.ts
  frontend/src/pages/History/History.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.stories.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
Labels: FE, feature

#140 리뷰 상세보기 페이지 구현 및 스토리 작성
  frontend/src/apis/apiClient.ts
  frontend/src/apis/review.ts
  frontend/src/assets/close.svg
  frontend/src/assets/notification.png
  frontend/src/components/Auth/OAuth/GithubOAuth.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Language/LanguageList.tsx
  frontend/src/components/Language/SpecPicker.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Reviewer/ReviewerCard/ReviewerCard.tsx
  frontend/src/components/Reviewer/ReviewerContentBox/ReviewerContentBox.stories.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/components/shared/ContentBox/ContentBox.stories.tsx
  frontend/src/components/shared/ContentBox/ContentBox.tsx
  frontend/src/components/shared/Navigation/Navigation.stories.tsx
  frontend/src/components/shared/Navigation/Navigation.tsx
  frontend/src/pages/History/History.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/ReviewDetail/ReviewDetail.stories.tsx
  frontend/src/pages/ReviewDetail/ReviewDetail.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/types/review.d.ts
  frontend/src/utils/constants/message.ts
Labels: FE, feature, refactor

#142 폼 유효성에 따른 UI 추가
  frontend/src/components/FormProvider/FormProvider.tsx
  frontend/src/components/FormProvider/InputField.tsx
  frontend/src/components/FormProvider/SubmitButton.tsx
  frontend/src/components/FormProvider/TextareaField.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/shared/Button/Button.stories.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/Input/Input.stories.tsx
  frontend/src/components/shared/Input/Input.tsx
  frontend/src/components/shared/Textarea/Textarea.stories.tsx
  frontend/src/components/shared/Textarea/Textarea.tsx
  frontend/src/hooks/useFormContext.ts
  frontend/src/pages/ReviewDetail/ReviewDetail.stories.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
Labels: FE, refactor

#143 z-index 수정
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/ModalProvider/Modal.tsx
  frontend/src/components/shared/Navigation/Navigation.tsx
  frontend/src/types/styled/common.d.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, fix, refactor

#139 refactor: 에러 메세지 배열 형태에서 객체로 변경
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/main/resources/static/docs/api.html
Labels: BE, refactor

#152 토큰 관리, 토큰 갱신, 재요청 기능 구현
  frontend/src/App.tsx
  frontend/src/apis/apiClient.ts
  frontend/src/apis/auth.ts
  frontend/src/components/Auth/AuthProvider/AuthProvider.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx
  frontend/src/hooks/useLocalStorage.ts
  frontend/src/hooks/useRevalidate.ts
  frontend/src/index.tsx
  frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/types/auth.d.ts
Labels: FE, feature

#155 NotFound 페이지 구현
  frontend/.storybook/preview.js
  frontend/src/App.tsx
  frontend/src/assets/not-found.png
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/pages/History/History.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/NotFound/NotFound.stories.tsx
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/ReviewDetail/ReviewDetail.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/utils/constants/path.ts
Labels: FE, feature

#153 내가 받은 리뷰 목록 조회 기능 구현
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/domain/Review.java
  backend/src/main/java/com/wootech/dropthecode/dto/ReviewSummary.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/ReviewSearchCondition.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ProfileResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ReviewResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ReviewsResponse.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepository.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustom.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImpl.java
  backend/src/main/java/com/wootech/dropthecode/repository/support/Querydsl4RepositorySupport.java
  backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
  backend/src/main/java/com/wootech/dropthecode/util/LocalDateTimeToArray.java
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java
Labels: BE, feature

#158 TeacherProfilie DB에 Member ID 적용되지 않는 버그 수정
  backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java
  backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
Labels: BE, bug, fix

#161 내가 리뷰한 리뷰 목록 조회 기능 구현
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/ReviewSearchCondition.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustom.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImpl.java
  backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java
  backend/src/test/java/com/wootech/dropthecode/service/ReviewServiceTest.java
Labels: BE, feature

#164 리뷰어 단일 조회
  backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java
  backend/src/main/java/com/wootech/dropthecode/service/TeacherService.java
  backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java
Labels: BE, feature

#160 ErrorBoundary 및 fallBack UI 구현
  frontend/.storybook/preview.js
  frontend/src/assets/error.gif
  frontend/src/assets/not-found.gif
  frontend/src/assets/not-found.png
  frontend/src/components/Error/Error.stories.tsx
  frontend/src/components/Error/Error.tsx
  frontend/src/components/Error/ErrorBoundary.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.stories.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/index.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/types/assets.d.ts
  frontend/src/types/review.d.ts
Labels: FE, feature

#157 리뷰 상태 업데이트 기능 구현
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/generated/com/wootech/dropthecode/domain/QReview.java
  backend/src/main/generated/com/wootech/dropthecode/domain/QTeacherProfile.java
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/Review.java
  backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java
  backend/src/main/java/com/wootech/dropthecode/exception/ReviewException.java
  backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
  backend/src/main/java/com/wootech/dropthecode/service/TeacherService.java
  backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
  backend/src/main/resources/application-local-init.properties
  backend/src/main/resources/static/docs/api.html
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
  backend/src/test/java/com/wootech/dropthecode/domain/ReviewTest.java
  backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java
Labels: BE, db change, feature

#169 토스트 컴포넌트 구현
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/close.svg
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/ToastProvider/Toast.stories.tsx
  frontend/src/components/ToastProvider/Toast.tsx
  frontend/src/components/ToastProvider/ToastButton.stories.tsx
  frontend/src/components/ToastProvider/ToastProvider.tsx
  frontend/src/components/Transititon/Transition.tsx
  frontend/src/components/shared/Chip/Chip.tsx
  frontend/src/components/shared/Input/Input.tsx
  frontend/src/components/shared/Textarea/Textarea.tsx
  frontend/src/hooks/useToastContext.ts
  frontend/src/types/styled/common.d.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, feature

#168 리뷰 상세 조회 기능 구현
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/ReviewResponse.java
  backend/src/main/java/com/wootech/dropthecode/exception/NotFoundException.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustom.java
  backend/src/main/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImpl.java
  backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
  backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
  backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java
  backend/src/test/java/com/wootech/dropthecode/service/ReviewServiceTest.java
Labels: BE, feature

#170 merge에서 제외된 z-index 다시 설정
  frontend/src/types/styled/common.d.ts
  frontend/src/utils/constants/theme.ts
Labels: FE, fix

#163 리뷰 생성 기능 구현
  backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
  backend/src/main/java/com/wootech/dropthecode/dto/request/ReviewCreateRequest.java
  backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
Labels: BE, feature

#181 babel preset 추가 및 설정 변경
  frontend/babel.config.js
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
Labels: FE, chore, fix

#184 테스트 환경설정
  frontend/.gitignore
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mock__/fileMock.ts
  frontend/src/__mock__/utils/testUtils.tsx
  frontend/src/setupTests.ts
Labels: 📚 chore 📚, 🕵🏻‍♀️ test 🕵🏻, 🧞‍♂️ FRONTEND 🧞‍♂️

#185 메인페이지 테스트
  frontend/src/__mock__/data/languages.ts
  frontend/src/__mock__/data/reviewers.ts
  frontend/src/__mock__/requestHandlers.ts
  frontend/src/components/Loading/Loading.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.stories.tsx
  frontend/src/components/shared/ContentBox/ContentBox.stories.tsx
  frontend/src/pages/Main/Main.test.tsx
Labels: 🕵🏻‍♀️ test 🕵🏻, 🧞‍♂️ FRONTEND 🧞‍♂️

#186 헤더 컴포넌트 테스트
  frontend/package-lock.json
  frontend/src/__mock__/data/auth.ts
  frontend/src/__mock__/fileMock.ts
  frontend/src/__mock__/server.ts
  frontend/src/__mock__/utils/mockingAuth.ts
  frontend/src/__mock__/utils/testUtils.tsx
  frontend/src/components/Header/Header.test.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/pages/History/History.tsx
  frontend/src/pages/Main/Main.test.tsx
  frontend/src/setupTests.ts
  frontend/src/types/review.d.ts
Labels: 🕵🏻‍♀️ test 🕵🏻, 🧞‍♂️ FRONTEND 🧞‍♂️

#187 api명세에 맞게 코드 수정 및 주석제거
  frontend/src/apis/review.ts
  frontend/src/components/Header/Header.test.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/components/shared/ContentBox/ContentBox.tsx
  frontend/src/types/route.d.ts
  frontend/src/utils/constants/route.ts
Labels: 🔨 refactor 🔨, 🧞‍♂️ FRONTEND 🧞‍♂️

#188 리뷰어 등록 페이지 선택된 언어, 기술스택 ui 개선
  frontend/src/components/Language/SpecPicker.tsx
Labels: 🔨 refactor 🔨, 🧞‍♂️ FRONTEND 🧞‍♂️

#182 Logback으로 Error 로그, Info 로그 남기기
  backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java
  backend/src/main/resources/appender/access-file-appender.xml
  backend/src/main/resources/appender/all-console-appender.xml
  backend/src/main/resources/appender/application-file-appender.xml
  backend/src/main/resources/appender/error-file-appender.xml
  backend/src/main/resources/appender/sql-file-appender.xml
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/logback-access.xml
  backend/src/main/resources/logback-spring.xml
Labels: 🔫 feature 🔫, 🧞‍♀️ BACKEND 🧞‍♀️

#190 data 초기화 email, name 바뀌는 오류 수정
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
Labels: 🧞‍♀️ BACKEND 🧞‍♀️, 🪲 bug 🪲

#193 Oauth 유저 정보 변경시 DB에 반영
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/oauth/OauthAttributes.java
  backend/src/main/java/com/wootech/dropthecode/domain/oauth/UserProfile.java
  backend/src/main/java/com/wootech/dropthecode/service/OauthService.java
  backend/src/test/java/com/wootech/dropthecode/domain/MemberTest.java
  backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
Labels: 🔫 feature 🔫, 🧞‍♀️ BACKEND 🧞‍♀️

#194 api요청 응답에 따른 메시지 토스트로 보여주는 기능
  frontend/src/__mock__/utils/testUtils.tsx
  frontend/src/components/Auth/AuthProvider/AuthProvider.tsx
  frontend/src/components/Language/LanguageList.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Review/ReviewList/ReviewList.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/components/ToastProvider/ToastPortal.tsx
  frontend/src/components/ToastProvider/ToastProvider.tsx
  frontend/src/hooks/useLanguageList.ts
  frontend/src/hooks/useRevalidate.ts
  frontend/src/hooks/useReviewerList.ts
  frontend/src/index.tsx
  frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/utils/constants/message.ts
  frontend/src/utils/validators/reviewRequestValidators.ts
  frontend/src/utils/validators/reviewerRegisterValidators.ts
Labels: 🔫 feature 🔫, 🧞‍♂️ FRONTEND 🧞‍♂️

#192 리뷰어 단일 조회 문서화 및 목록 조회 정렬 클래스 변경
  backend/src/docs/asciidoc/api.adoc
  backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherPaginationResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TechSpecResponse.java
  backend/src/main/java/com/wootech/dropthecode/repository/TeacherFilterRepositoryImpl.java
  backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
Labels: 📝 docs 📝, 🔨 refactor 🔨, 🔫 feature 🔫, 🧞‍♀️ BACKEND 🧞‍♀️

#196 Member 도메인에 github url 추가 및 테스트 수정
  backend/src/main/generated/com/wootech/dropthecode/domain/QMember.java
  backend/src/main/java/com/wootech/dropthecode/domain/Member.java
  backend/src/main/java/com/wootech/dropthecode/domain/oauth/OauthAttributes.java
  backend/src/main/java/com/wootech/dropthecode/domain/oauth/UserProfile.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/LoginResponse.java
  backend/src/main/java/com/wootech/dropthecode/service/OauthService.java
  backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
  backend/src/test/java/com/wootech/dropthecode/controller/AuthControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java
  backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
  backend/src/test/java/com/wootech/dropthecode/domain/MemberTest.java
  backend/src/test/java/com/wootech/dropthecode/domain/ReviewTest.java
  backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java
  backend/src/test/java/com/wootech/dropthecode/service/AuthServiceTest.java
  backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
Labels: 🔫 feature 🔫, 🗄 DB change 🗄, 🧞‍♀️ BACKEND 🧞‍♀️

#198 members/me, 리뷰어 상세 조회, 리뷰어 전체 조회 시 응답에 github url 필드 추가
  backend/src/main/java/com/wootech/dropthecode/dto/response/MemberResponse.java
  backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java
  backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java
  backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
Labels: 🔫 feature 🔫, 🗄 DB change 🗄, 🧞‍♀️ BACKEND 🧞‍♀️

#197 리뷰어 목록 조회 정렬 버그 및 쿼리 로깅 수정
  backend/src/main/java/com/wootech/dropthecode/repository/TeacherFilterRepositoryImpl.java
  backend/src/main/resources/logback-spring.xml
Labels: 🔨 refactor 🔨, 🛠 fix 🛠, 🧞‍♀️ BACKEND 🧞‍♀️

#200 앱 UI 리팩터링
  frontend/src/__mock__/utils/testUtils.tsx
  frontend/src/apis/review.ts
  frontend/src/assets/down_arrow.svg
  frontend/src/assets/up_arrow.svg
  frontend/src/components/CareerPicker/CareerPicker.tsx
  frontend/src/components/GlobalStyle/GlobalStyle.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Language/LanguageList.tsx
  frontend/src/components/Language/SpecPicker.tsx
  frontend/src/components/MenuItemButton/MenuItemButton.tsx
  frontend/src/components/Review/ReviewCard/ReviewCard.tsx
  frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx
  frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx
  frontend/src/components/Reviewer/ReviewerCard/ReviewerCard.tsx
  frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/components/ToastProvider/Toast.stories.tsx
  frontend/src/components/ToastProvider/ToastProvider.tsx
  frontend/src/components/shared/Button/Button.tsx
  frontend/src/components/shared/ContentBox/ContentBox.tsx
  frontend/src/components/shared/Input/Input.tsx
  frontend/src/components/shared/Navigation/Navigation.tsx
  frontend/src/components/shared/Select/Select.tsx
  frontend/src/components/shared/TextBox/TextBox.tsx
  frontend/src/components/shared/Textarea/Textarea.tsx
  frontend/src/hooks/useLanguageList.ts
  frontend/src/index.tsx
  frontend/src/pages/History/History.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/pages/ReviewDetail/ReviewDetail.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx
  frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
  frontend/src/theme/theme.ts
  frontend/src/types/styled/common.d.ts
  frontend/src/utils/constants/size.ts
Labels: 🔨 refactor 🔨, 🗣 discussion 🗣, 🛠 fix 🛠, 🧞‍♂️ FRONTEND 🧞‍♂️

#201 token을 통한 로그인 유지 기능 오류 수정
  frontend/src/__mock__/utils/mockingToken.ts
  frontend/src/apis/auth.ts
  frontend/src/components/Auth/AuthProvider/AuthProvider.tsx
  frontend/src/components/Header/Header.test.tsx
  frontend/src/hooks/useRevalidate.ts
  frontend/src/utils/constants/key.ts
Labels: 🛠 fix 🛠, 🧞‍♂️ FRONTEND 🧞‍♂️

#202 리뷰어 상세보기 페이지 테스트
  frontend/src/__mock__/data/auth.ts
  frontend/src/__mock__/data/reviews.ts
  frontend/src/__mock__/server.ts
  frontend/src/components/Header/Header.test.tsx
  frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx
  frontend/src/pages/ReviewerDetail/ReviewerDetail.test.tsx
  frontend/src/setupTests.ts
Labels: 🕵🏻‍♀️ test 🕵🏻, 🧞‍♂️ FRONTEND 🧞‍♂️
